### ISSUE TITLE
Error in schema for cp_mgmt_access_rules_module for VPN

### ISSUE THREAD

**Issue by Smixi** [CheckPointSW/CheckPointAnsibleMgmtCollection#107]
Hi,

I'm trying to add a rule using this Ansible module.

I figured out that rules that I push that are not using the VPN attribute are created, but those using it fail.

E.g :
```yaml
- name: Create access rules
  check_point.mgmt.cp_mgmt_access_rules:
    layer: "{{item.layer}}"
    rules: 
      - name: 'RuleName'
        source: 
          - 'RuleSource'
        destination: 
          - 'RuleDest'
        vpn: 
          - community: 
              - name: Any
```
The documentation is unclear of what the community object must look like. I expected something like above, but it returned 

``` 
msg: "value of vpn must be one of: Any, All_GwToGw, got: [{'community': [{'name': 'Any'}]}]"}}
```

So I tried to use something like 

`        vpn: 
          - Any
`

or even 
`        vpn: Any
`
which outputs : "msg": "dictionary requested, could not parse JSON or key=value"} 

It's seems that the webservice documentation uses the later, which is not parsed correctly by ansible because it is defined as having dict elements. 

Do you have any recommandation ?

Thanks in advance :).
