### ISSUE TITLE
The invalid value: [interoperable-device]'

### ISSUE THREAD

**Issue by adelson-silva** [CheckPointSW/CheckPointAnsibleMgmtCollection#147]
I am facing an error when trying to create a new interoperable device.
**_"msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter', 'message': 'Invalid parameter for [type]. The invalid value: [interoperable-device]'}"_**

Playbook example:
```
---
- name: playbook name
  hosts: check_point
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_network_os: check_point.mgmt.checkpoint
     ansible_checkpoint_domain: domainX

  tasks:
  - name: add-interoperable-device
    check_point.mgmt.cp_mgmt_interoperable_device:
      ip_address: "192.168.1.6"
      name: "NewInteroperableDevice"
      auto_publish_session: true
      state: present
```
