### ISSUE TITLE
cp_mgmt_https_rule - generic internal error

### ISSUE THREAD

**Issue by doritoes** [CheckPointSW/CheckPointAnsibleMgmtCollection#153]
Issues with cp_mgmt_https_rule failing with internal error.

check_point.mgmt 6.2.1 - SMS R81.20 JHF 82

Example task:

```
    - name: add https rule
      check_point.mgmt.cp_mgmt_https_rule:
        layer: Default Layer
        name: test
        source:
          - Any
        destination:
          - Internet
        service:
          - HTTPS default services
        action: Inspect
        track:
          type: Log
        comments: first rule
        position: 1
    - name: discard changes
       check_point.mgmt.cp_mgmt_discard:
```

Checkpoint device returned error 500 with message {'code': 'generic_internal_error', 'message': 'Internal error. For more info search for [78982141ec-88e6-412b1961c685] in log file'

From api.elg: "Unrecognized field "name" (class com.checkpoint.management.web_api.core.handler.objects.rulebases.rules.tls.TLSRuleIdentifierRequest), not marked as ignorable (11 known properties: "uid", "layer", "async-response", "deepest-details-level", "constant-uid", "details-level", "rule-number", "resolve", "fields-to-return", "DnsProcessGroup", "dereference-max-depth"][...]

SmartConsole shell succeeded:
succeeded: add-https-rule layer "Default Layer" position 1 name "test" source "Any" destination "Internet" service "HTTPS default services"
