### ISSUE TITLE
cp_mgmt_host - err_validation_failed when modifying objects

### ISSUE THREAD

**Issue by doritoes** [CheckPointSW/CheckPointAnsibleMgmtCollection#154]
EDIT: I update the issue name to clarify this is only affecting management SMS object

A common task is to modify the sms object to add autonat. The module seems to use add-host instead of set-host.

Example:
  tasks:
    - name: add NAT to sms
      check_point.mgmt.cp_mgmt_host:
        name: sms
        ipv4_address: 192.168.41.20
        color: dark blue
        comments: SMS
        nat_settings:
          auto_rule: true
          hide_behind: ip-address
          ip_address: 192.168.101.7
          method: hide
        state: present

Error:
Checkpoint device returned error 400 with message {'code': 'err_validation_failed', 'message': 'Validation failed with 1 warning and 1 error', 'warnings': [{'message': 'Multiple objects have the same IP address 192.168.41.20'}], 'errors': [{'message': \"More than one object named 'sms' exists'\"}]} Unpublished changes were discarded"}

**Comment by chkp-edenbr** [comment]
Hi,
I wasn't able to recreate the issue. 
Please specify the exact use case (yaml files you are running each time - for add and set) and add the log file $MDS_FWDIR/log/api.elg as well as your machine's version.
Would be best if you could try running it again as you did and then send the logs so they could contain the relevant data.

**Comment by doritoes** [comment]
This may be a case where the management API (and therefore Ansible) cannot work with the SMS objects. If this is so, let me know so I can submit an RFE.

Detailed use case
1) Set up a new SMS named "sms". The object "sms" is automatically created.
2) Configure SMS to allow Ansible playbooks to run such as the following sample

```
---
- name: Create branch1 objects
  hosts: check_point
  connection: httpapi
  tasks:
    - name: management network NAT
      check_point.mgmt.cp_mgmt_network:
        name: management_192.168.41.0/24
        subnet: 192.168.41.0
        mask_length: 24
        color: crete blue
        comments: management network
        nat_settings:
          auto_rule: true
          hide_behind: ip-address
          ip_address: 192.168.101.4
          method: hide
        state: present
    - name: branch 1 outbound NAT
      check_point.mgmt.cp_mgmt_host:
        name: branch1_outbound_nat
        ipv4_address: 192.168.101.4
        color: dark blue
        comments: branch1 outbound NAT
        state: present
```

3) Create an ansible playbook to add automatic NAT to the SMS to allow it to manage external gateways

Example:

```
---
- name: Enable NAT on sms
  hosts: check_point
  connection: httpapi
  tasks:
  - name: add NAT to sms
    check_point.mgmt.cp_mgmt_host:
      name: sms
      ipv4_address: 192.168.41.20
      color: dark blue
      comments: SMS
      nat_settings:
        auto_rule: true
        hide_behind: ip-address
        ip_address: 192.168.101.7
        method: hide
      state: present
```

Expected behavior: update object SMS with the auto NAT using Check Point Management API set-host

What actually happens: it fails with a message indicating it was using add-host
Checkpoint device returned error 400 with message {'code': 'err_validation_failed', 'message': 'Validation failed with 1 warning and 1 error', 'warnings': [{'message': 'Multiple objects have the same IP address 192.168.41.20'}], 'errors': [{'message': "More than one object named 'sms' exists'"}]} Unpublished changes were discarded"}

cp_mgmt_host overloads add-host, set-host, delete-host.

The examples in documentation list the following examples:

```
- name: add-host
  cp_mgmt_host:
    ip_address: 192.0.2.1
    name: New Host 1
    state: present
- name: set-host
  cp_mgmt_host:
    color: green
    ipv4_address: 192.0.2.2
    name: New Host 1
    state: present
- name: set-host with NAT
  cp_mgmt_host:
    name: New Host 1
    state: present
      nat_settings:
        auto_rule: true
        hide_behind: ip-address
        ip_address: 192.168.101.7
        method: hide
- name: delete-host
  cp_mgmt_host:
    name: New Host 1
    state: absent
```

Note that the set example FAILS on because "green" is not a valid color (I'm on R81.10). Therefore I am using "dark green".

Note this testcase us successful.

testcase.yml

```
---
- name: test case
  hosts: check_point
  connection: httpadpi
  tasks:
    - name: add-host
     check_point.mgmt. cp_mgmt_host:
        ip_address: 192.0.2.1
        name: New Host 1
        state: present
    - name: set-host
      check_point.mgmt.cp_mgmt_host:
        color: dark green
        ipv4_address: 192.0.2.2
        name: New Host 1
        state: present
    - name: set-host with hide NAT
      check_point.mgmt.cp_mgmt_host:
        name: New Host 1
        nat_settings:
          auto_rule: true
          hide_behind: ip-address
          ip_address: 192.168.101.7
        state: present
    - name: set-host with static NAT
      check_point.mgmt.cp_mgmt_host:
        name: New Host 1
        nat_settings:
          auto_rule: true
          ip_address: 192.168.101.7
          method: static
        state: present
    - name: delete-host
      check_point.mgmt.cp_mgmt_host:
        name: New Host 1
        state: absent
    - name: discard changes
      check_point.mgmt.cp_mgmt_discard:
```

Now repeating with the object sms (the SMS)
testcase.yml

```
---
- name: test case
  hosts: check_point
  connection: httpadpi
  tasks:
     - name: set-host with static NAT
      check_point.mgmt.cp_mgmt_host:
        name: sms
        nat_settings:
          auto_rule: true
          ip_address: 192.168.101.7
          method: static
        state: present
    - name: publish changes
      check_point.mgmt.cp_mgmt_publish:
```

This fails with error 400
Missing parameter: [ip-address/ipv4-address/ipv6-address]

Adding the IP address:

```
---
- name: test case
  hosts: check_point
  connection: httpadpi
  tasks:
     - name: set-host with static NAT
      check_point.mgmt.cp_mgmt_host:
        name: sms
        ip_address: 102.168.41.20
        nat_settings:
          auto_rule: true
          ip_address: 192.168.101.7
          method: static
        state: present
    - name: publish changes
      check_point.mgmt.cp_mgmt_publish:
```

This fails with error 400
Multiple objects have the same IP address 192.168.41.20

Why this matters: for SMS to remotely manage gateways, static NAT is used. Automating this would remove another manual task in SmartConsole.

Also the check box "Apply for Security Gateway control connections."
