### ISSUE TITLE
Missing identifying parameter in params. Missing parameter: [uid]

### ISSUE THREAD

**Issue by chuegel** [CheckPointSW/CheckPointAnsibleMgmtCollection#160]
When I try to add a interface to an existing cluster using the example from: https://docs.ansible.com/ansible/devel/collections/check_point/mgmt/cp_mgmt_interface_module.html

```
- name: Add interfaces to cluster in management
  check_point.mgmt.cp_mgmt_interface:
    anti_spoofing: "{{ item.anti_spoofing }}"
    anti_spoofing_settings:
      action: detect
      exclude_packets: false
      spoof_tracking: log
    cluster_members:
      - ipv4_address: "{{ item.fw_node1_ipv4_address }}"
        ipv4_mask_length: "{{ item.fw_mask_length }}"
        ipv4_network_mask: "{{ item.mask }}"
        member_name: "{{ CSV_CONTENT.list[0].fw_node1_name }}"
#        uid: "{{ item.fw_node1_uid }}"
        name: "{{ item.interface }}"
      - ipv4_address: "{{ item.fw_node2_ipv4_address }}"
        ipv4_mask_length: "{{ item.fw_mask_length }}"
        ipv4_network_mask: "{{ item.mask }}"
        member_name: "{{ CSV_CONTENT.list[0].fw_node2_name }}"
#        uid: "{{ item.fw_node2_uid }}"
        name: "{{ item.interface }}"
    cluster_network_type: "{{ item.cluster_interface_type }}"
    gateway_uid: "{{ item.fw_cluster_uid }}"
    ignore_warnings: false
    ipv4_address: "{{ item.fw_cluster_ip }}"
    ipv4_mask_length: "{{ item.fw_mask_length }}"
    name: "{{ item.interface }}"
    state: "{{ item.state }}"
    topology: "{{ item.topology }}"
    topology_settings:
      interface_leads_to_dmz: false
      ip_address_behind_this_interface: "{{ item.topology_settings }}"
    auto_publish_session: true
  loop: "{{ CSV_NEW_CONTENT }}"
```
the task fails with the error:

 ```
 msg: 'Checkpoint device returned error 400 with message {''code'': ''generic_err_missing_required_parameters'', ''message'': ''Missing identifying parameter in params. Missing parameter: [uid]''}'
``` 
Then I tried to add the member uids (see above the commented lines)  but it also fails with:

```
msg: 'Unsupported parameters for (check_point.mgmt.cp_mgmt_interface) module: cluster_members.uid. Supported parameters include: color, comments, details_level, ignore_errors, ignore_warnings, ip_address, ipv4_address, ipv4_mask_length, ipv4_network_mask, ipv6_address, ipv6_mask_length, ipv6_network_mask, mask_length, member_name, name, network_mask, tags.'
```
What is the correct way to add a interface to an existing cluster?
Thanks

Collection versions :
`check_point.mgmt              6.2.1 `

Ansible version:
```
ansible [core 2.15.12]
  config file = /home/chuegel/development/github/nw-playbooks/ansible.cfg
  configured module search path = ['/home/chuegel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/chuegel/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/chuegel/development/github/nw-playbooks/collections/ansible_collections
  executable location = /home/chuegel/venv/bin/ansible
  python version = 3.9.19 (main, May 16 2024, 08:45:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/home/chuegel/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```
