### ISSUE TITLE
ansible_checkpoint_domain changes domain only when waiting for 30 seconds

### ISSUE THREAD

**Issue by ms0mmer** [CheckPointSW/CheckPointAnsibleMgmtCollection#178]
I habe a MDS enviroment and try to change the domain between tasks. Therefore I created 2 hosts in the inventory with different ansible_checkpoint_domains.

```
ansible-inventory --host mds-global |grep "ansible_checkpoint_domain"
    "ansible_checkpoint_domain": "Global",

ansible-inventory --host mds-office |grep "ansible_checkpoint_domain"
    "ansible_checkpoint_domain": "Office",
```
Now here's a simple playbook, that should read some facts from both domains, but both tasks only show the hosts  for the first domain (Office) 

```
- hosts: localhost
  connection: httpapi
  serial: 1
  gather_facts: false

  tasks:

  - name: show-checkpoint-host-office
    check_point.mgmt.cp_mgmt_checkpoint_host_facts:
      limit: 10
    delegate_to: mds-office 

  - name: show-checkpoint-host-global
    check_point.mgmt.cp_mgmt_checkpoint_host_facts:
      limit: 10
    delegate_to: mds-global
```
The strange thing is, if I do an additional` wait_for: `between the tasks (min. 30 seconds) it suddenly starts working. 

im wondering if  this is expected behaviour and where  this 30 seconds do come from?

EDIT:
Ansible 2.14.18
check_point.mgmt 6.4.1
