### ISSUE TITLE
"ansible_checkpoint_domain" variable doesn't work.

### ISSUE THREAD

**Issue by gmoraa** [CheckPointSW/CheckPointAnsibleMgmtCollection#21]
According to the existing documentation you can switch domains by making use of the variable "**ansible_checkpoint_domain**" but that doesn't work, instead what's happening is the API calls are going locally. 

Apparently my parameters are be fine because if I try the same from Postman the changes are reflected as expected.

`ansible 2.9.7
`

```
- name: example_playbook
  hosts: check_point
  connection: httpapi
  tasks:
    - name: set-service-tcp
      cp_mgmt_service_tcp:
      name: %SERVICE%
      ...
      auto_publish_session: yes

    vars:
      ansible_checkpoint_domain: "%DOMAIN%"
```
