### ISSUE TITLE
cp_mgmt_access_rule no changes when using user_check, but unpublished changes on management

### ISSUE THREAD

**Issue by alex-barth** [CheckPointSW/CheckPointAnsibleMgmtCollection#38]
Hi,

I have another problem with the **cp_mgmt_access_rule** module:
It has something to do with the `user_check` variable. When this is parameter is set and changed, ansible will report this as no changes, but the rule will be locked for modification on the management. Even if there are no changes, but `user_check` is set, the rule will be locked and unpublished changes remain. A subsequent policy install will then throw an error "unpublished changes".
For now we just always publish manually (by calling `cp_mgmt_publish`) afterwards as a workaround and set the `changed_when` depending on the published changes.

**playbook**
```yaml
---
- name: recreate issue 38
  hosts: all
  gather_facts: no
  connection: httpapi
  vars:
    ansible_python_interpreter: auto
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: check_point.mgmt.checkpoint

  tasks:
    - name: remove rule for clean test
      cp_mgmt_access_rule:
        layer: "Network"
        name: "rule 1"
        state: absent

    # rule does not yet exists and is sucessfully published
    - name: create rule with user_check interaction
      cp_mgmt_access_rule:
        layer: "Network"
        position: "1"
        name: "rule 1"
        source: "Any"
        destination: "Any"
        service: "ssh"
        action: "Drop"
        user_check:
          interaction: "Blocked Message - Access Control"
        state: present
        auto_publish_session: true
    
    # already published, nothing changed
    - name: publish manually - report changed when (publishedChanges > 0)
      cp_mgmt_publish:
      register: __changes
      changed_when: __changes['publish']['tasks'][0]['task-details'][0]['publishResponse']['numberOfPublishedChanges'] > 0

    # rule exists, no changes are reported - but interaction removed, no automatic publish, but rule is locked
    - name: remove user_check interaction from rule - should report changed
      cp_mgmt_access_rule:
        layer: "Network"
        position: "1"
        name: "rule 1"
        source: "Any"
        destination: "Any"
        service: "ssh"
        action: "Drop"
        user_check:
          interaction: null
        state: present
        auto_publish_session: true

    # publish rule modification, 1 change
    - name: publish manually - report changed when (publishedChanges > 0)
      cp_mgmt_publish:
      register: __changes
      changed_when: __changes['publish']['tasks'][0]['task-details'][0]['publishResponse']['numberOfPublishedChanges'] > 0

    # rule exists, no changes are reported - nothing changed, no automatic publish, but rule is locked
    - name: rule has not changed - but unpublished changes remain
      cp_mgmt_access_rule:
        layer: "Network"
        position: "1"
        name: "rule 1"
        source: "Any"
        destination: "Any"
        service: "ssh"
        action: "Drop"
        user_check:
          interaction: null
        state: present
        auto_publish_session: true

    # publish rule modification, 1 change
    - name: publish manually - report changed when (publishedChanges > 0)
      cp_mgmt_publish:
      register: __changes
      changed_when: __changes['publish']['tasks'][0]['task-details'][0]['publishResponse']['numberOfPublishedChanges'] > 0

```
**output**
```
PLAY [recreate issue 38] *******************************************************************************************
TASK [remove rule for clean test] **********************************************************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [create rule with user_check interaction] *********************************************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [publish manually - report changed when (publishedChanges > 0)] ***********************************************
ok: [T-ORC-FW-MGT-ABARTH]

TASK [remove user_check interaction from rule - should report changed] *********************************************
ok: [T-ORC-FW-MGT-ABARTH]

TASK [publish manually - report changed when (publishedChanges > 0)] ***********************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [rule has not changed - but unpublished changes remain] *******************************************************
ok: [T-ORC-FW-MGT-ABARTH]

TASK [publish manually - report changed when (publishedChanges > 0)] ***********************************************
changed: [T-ORC-FW-MGT-ABARTH]

PLAY RECAP *********************************************************************************************************
T-ORC-FW-MGT-ABARTH        : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Please tell me if you need additional information.

Thanks,
Alex
