### ISSUE TITLE
Cannot create domain and then add objects to it.

### ISSUE THREAD

**Issue by Smixi** [CheckPointSW/CheckPointAnsibleMgmtCollection#54]
Hi,

I've been trying to automate CMA deployment using Ansible. To do that, I use two role. One for creating the CMA using ansible host without the "ansible_checkpoint_domain" and then another role that use it with the name of the CMA I created:

```
ckps:
  hosts:
    mdm:
      ansible_host: a.a.a.a
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_user: user
      ansible_password: password
      ansible_httpapi_port: 443
      ansible_network_os: check_point.mgmt.checkpoint
      domain: test_domain
      cma_name: test_cma
      mds: mds_name
      cma_ip: "x.x.x.x"
    cma:
      ansible_host: a.a.a.a
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_user: user
      ansible_password: password
      ansible_httpapi_port: 443
      ansible_network_os: check_point.mgmt.checkpoint
      ansible_checkpoint_domain: test_domain
```

with main role:

```
- name: Create CMA
  hosts: mdm
  connection: httpapi
  roles:
    - add_cma
- name: Insert default objects
  hosts: cma
  connection: httpapi
  roles:
    - create_cma_objects
```

Creating the CMA works like a charm using: 
```
- name: Create CMA
  check_point.mgmt.cp_mgmt_add_domain:
    name: "{{ domain }}"
    servers:
      - ip_address: "{{ cma_ip }}"
        multi_domain_server: "{{ mds }}"
        name: "{{ cma_name }}"

- name: Add trusted clients for API
  check_point.mgmt.cp_mgmt_trusted_client:
    name: AnyHost
    state: present
    domains_assignment: "{{ domain }}"
    auto_publish_session: yes
```

but then,  in my role where i create object in the CMA (with the host with the specified domain):

```
- name: add-host
  cp_mgmt_host:
    ip_address: "{{ item.get('ipv4-address') }}"
    name: "{{ item.name }}"
    comments: "{{ item.comments }}"
    state: present
  loop: "{{ hosts.list }}"
```

it crashes, and says:
```
failed: [cma] (item={'name': 'name', 'ipv4-address': 'y.y.y.y', 'comments': 'some commment'}) => {"ansible_loop_var": "item", "changed": false, "item": {"comments": "some comment", "ipv4-address": "y.y.y.y", "name": "name"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/sami/.ansible/tmp/ansible-local-29740hyz_1fy5/ansible-tmp-1642418637.9183214-30174-87115745096485/AnsiballZ_cp_mgmt_host.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/sami/.ansible/tmp/ansible-local-29740hyz_1fy5/ansible-tmp-1642418637.9183214-30174-87115745096485/AnsiballZ_cp_mgmt_host.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sami/.ansible/tmp/ansible-local-29740hyz_1fy5/ansible-tmp-1642418637.9183214-30174-87115745096485/AnsiballZ_cp_mgmt_host.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cp_mgmt_host_payload_zm5xyskm/ansible_cp_mgmt_host_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_host.py\", line 333, in <module>\n  File \"/tmp/ansible_cp_mgmt_host_payload_zm5xyskm/ansible_cp_mgmt_host_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_host.py\", line 328, in main\n  File \"/tmp/ansible_cp_mgmt_host_payload_zm5xyskm/ansible_cp_mgmt_host_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py\", line 278, in api_call\n  File \"/tmp/ansible_cp_mgmt_host_payload_zm5xyskm/ansible_cp_mgmt_host_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py\", line 71, in send_request\n  File \"/tmp/ansible_cp_mgmt_host_payload_zm5xyskm/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: <ns1:XMLFault xmlns:ns1=\"http://cxf.apache.org/bindings/xformat\"><ns1:faultstring xmlns:ns1=\"http://cxf.apache.org/bindings/xformat\">com.checkpoint.management.web_api_is.exceptions.WebApiGeneralException</ns1:faultstring></ns1:XMLFault>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

as If the targeted domain wasn't specified in the connection.

I'm using this Ansible version, and just runned ansible-galaxy to install the checkpoint module
```
ansible --version
ansible [core 2.11.7] 
  config file = None
  configured module search path = ['/home/sami/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sami/.local/lib/python3.7/site-packages/ansible
  ansible collection location = /home/sami/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sami/.local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.0.2
  libyaml = True
```

Meanwhile, when I execute the role independantly by using two ansible-playbook commands, it does works properly. It seems it doesn't login again and credentials failed ?

How can I execute roles on MDS and multiple domains without invoking ansible-playbook multiple time ?

Thanks in advance for your answer, I can add info if needed.

Regards,
