### ISSUE TITLE
 Missing parameter in Global assignment even though all required parameters are declared

### ISSUE THREAD

**Issue by sasikdar** [CheckPointSW/CheckPointAnsibleMgmtCollection#87]
```
- name: add-global-assignment
  check_point.mgmt.cp_mgmt_global_assignment:
    dependent_domain: Domain-4 
    global_access_policy: standard
    global_domain: Global
    global_threat_prevention_policy: standard
    manage_protection_actions: true
    state: present
```
output trace:
TASK [assign-global-policies : add-global-assignment] ***************************************************************************************************************************************************************************************
fatal: [host-of-my-choice]: FAILED! => {"changed": false, "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_missing_required_parameters', 'message': \"Missing identifying parameter in params. Missing parameter: ['uid' or 'global-domain'-'dependent-domain' pair]\"}"}
