### ISSUE TITLE
Cluster registration fails with invalid paramter cluster_version 

### ISSUE THREAD

**Issue by sasikdar** [CheckPointSW/CheckPointAnsibleMgmtCollection#90]
```

- name: Register Cluster
  check_point.mgmt.cp_mgmt_simple_cluster:
    cluster_mode: cluster-xl-ha
    color: "{{ cluster.color }}"
    firewall: true
    interfaces: "{{ cluster.interfaces }}"
    ip_address: "{{ cluster.ip_address }}"
    members: "{{ cluster.members }}"
    name: "{{ cluster.name }}"
    os_name: Gaia
    state: present
    cluster_version: R81.20
    send_logs_to_server: "{{ cluster.send_logs_to_server }}"
    firewall_settings:
      auto_maximum_limit_for_concurrent_connections: False
      maximum_limit_for_concurrent_connections: 250000
    comments: "{{ cluster.name }} Gateway Cluster"
    hardware: Open server
    auto_publish_session: True
  when: cluster.name not in existing_clusters
  loop: "{{ domain_inventory.clusters }}"
  loop_control:
    loop_var: cluster
  vars:
    ansible_checkpoint_domain: "{{ domain_inventory.name }}"
```

error message :

failed: [Domain-5]  "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter [cluster-version]'} Unpublished changes were discarded"}
